src/Entity/Records.php
<?php

namespace App\Entity;

use App\Repository\RecordsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecordsRepository::class)
 */
class Records
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $User;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Score;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $WhiteTest;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Certification;

    /**
     * @ORM\Column(type="date", length=255)
     */
    private $Date;

    /**
     * @ORM\Column(type="integer")
     */
    private $Total;

    /**
     * @ORM\ManyToOne(targetEntity=User1::class, inversedBy="records")
     */
    private $User1;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?string
    {
        return $this->User;
    }

    public function setUser(string $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getScore(): ?string
    {
        return $this->Score;
    }

    public function setScore(string $Score): self
    {
        $this->Score = $Score;

        return $this;
    }

    public function getWhiteTest(): ?string
    {
        return $this->WhiteTest;
    }

    public function setWhiteTest(string $WhiteTest): self
    {
        $this->WhiteTest = $WhiteTest;

        return $this;
    }

    public function getCertification(): ?string
    {
        return $this->Certification;
    }

    public function setCertification(string $Certification): self
    {
        $this->Certification = $Certification;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->Total;
    }

    public function setTotal(int $Total): self
    {
        $this->Total = $Total;

        return $this;
    }

    public function getUser1(): ?User1
    {
        return $this->User1;
    }

    public function setUser1(?User1 $User1): self
    {
        $this->User1 = $User1;

        return $this;
    }
}

src/Form/RecordsType.php
<?php

namespace App\Form;

use App\Entity\Records;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecordsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('User')
            ->add('Score')
            ->add('WhiteTest')
            ->add('Certification')
            ->add('Date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Records::class,
        ]);
    }
}

src/Controller/RecordsController.php
<?php

namespace App\Controller;

use App\Entity\RDV;
use App\Entity\Records;
use App\Form\RecordsType;
use App\Repository\RecordsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/records')]
class RecordsController extends AbstractController
{
    #[Route('/', name: 'records_index', methods: ['GET'])]
    public function index(RecordsRepository $recordsRepository): Response
    {
        return $this->render('records/index.html.twig', [
            'records' => $recordsRepository->findByOrder($this->getUser()->getLog())
            ,'user'=>$this->getuser()
            , 'alertrdv'=>count($this->getDoctrine()->getManager()->getRepository(RDV::class)->findBy(['Status'=>"Pending"]))
        ]);
    }
    #[Route('/deleteallrec', name: 'deleteallrec', methods: ['GET','POST'])]
    public function edit(): Response
    {
        $em=$this->getDoctrine()->getManager();
        $record=$em->getRepository(Records::class)->findAll();
        $i=0;
        while($i!=count($record)){
            $em->remove($record[$i]);
            $em->flush();
            $i++;
        }
        return $this->redirectToRoute('records_index',['user'=>$this->getuser()]);
    }

    /**
     * @Route ("/deleterec/{id}",name="deleterec")
     */
   public function deleterecord(int $id):Response
   {
       $em=$this->getDoctrine()->getManager();
       $record=$em->getRepository(Records::class)->find($id);
       $em->remove($record);
       $em->flush();
       return $this->redirectToRoute('records_index',['user'=>$this->getuser()]);
   }
}

templates/records/index.html.twig
{%  extends "Client/base.html.twig" %}
{% block title %}Add WhiteTest{% endblock %}


{%  block comment  %}<!--Menu just replace the parent with the link here and add the word "active" to the class= for the current page name-->
    <!-- <li class="nav-item active"><a href="" class="nav-link">Forum</a></li> -->{% endblock %}

{% block home %} {{ parent() }} {% endblock %}
{% block about %} {{ parent() }} {% endblock %}
{% block certifications %} {{ parent() }} {% endblock %}
{% block instructors %} {{ parent() }} {% endblock %}
{% block forum %}  {{ parent() }} {% endblock %}
{% block contact %} {{ parent() }} {% endblock %}


{%  block sectionname %} Test Records <div id="m"></div>{% endblock %}
{% block sectionmenu %} WhiteTest {% endblock %}

{% block contenu %}

    <table class="table table-hover" id="tab">
        <thead class="thead-dark">
            <tr>
                <th>User</th>
                <th>Score</th>
                <th>WhiteTest</th>
                <th>Certification</th>
                <th>Date</th>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for record in records %}
            <tr>
                <td>{{ record.User }}</td>
                <td>{{ ((record.score*100)/record.total)|round(2) }}%</td>
                <td>{{ record.WhiteTest }}</td>
                <td>{{ record.Certification }}</td>
                <td>{{ record.Date ? record.Date|date('Y-m-d') : '' }}</td>
                <td>
                    <div class="svg-wrapper-red" style="float: left;">
                        <svg height="40" width="150" xmlns="http://www.w3.org/2000/svg">
                            <rect id="shape-red" height="40" width="150" />
                            <div id="text" >
                                &nbsp;<a href="{{ path('deleterec',{id:record.Id}) }}"><span class="spot"></span><span style="color: black;">Delete</span></a>
                            </div>
                        </svg>
                    </div>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7"><center class="unselectable">No Test Records Found</center></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if records!=null %}
        <center>
        <div class="svg-wrapper-red">
            <svg height="40" width="150" xmlns="http://www.w3.org/2000/svg">
                <rect id="shape-red" height="40" width="150" />
                <div id="text" >
                    &nbsp;<a href="#m" onclick="confdelete()"><span class="spot"></span><span style="color: black;">Delete All</span></a>
                </div>
            </svg>
        </div>
        </center>
    {% endif %}

    <style>
        .unselectable {
            -webkit-user-select: none;
            -webkit-touch-callout: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
        .unclick{ text-decoration: none; cursor: default; }
    </style>
    <style>
        /*       Just setting CSS for the page   */

        * {
            margin: 0;
            padding: 0;
        }

        html,
        css {
            width: 100%;
            height: 100%;
        }

        .position {
            margin-left: auto;
            margin-right: auto;
            text-align: center;
            margin-top: 15%;
        }

        #workarea {
            position: absolute;
            width: 100%;
            height: 100%;
            background-color: #1e1a3e;
            font-family: Raleway;
        }

        #personal {
            color:white;
            text-decoration:none;
            position:absolute;
            bottom:15px;
            right:2%;
        }
        /*    start code for the actual button:         */


        /*
            Spot is the span on the inside of the href that
            fills the parent and makes the hover and link work
            for the entire div
        */

        .spot {
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
        }
        /*
            This is the outer svg wrapper that the SVG itself will
            fill. Multiple svg-wrapper classes can be put side by side.
        */

        .svg-wrapper {
            margin-top: 0;
            position: relative;
            width: 150px;
            /*make sure to use same height/width as in the html*/
            height: 40px;
            display: inline-block;
            border-radius: 3px;
            margin-left: 5px;
            margin-right: 5px
        }
        /*
          This is where we define the fill, color, thickness,
          and stroke pattern of the SVG when there is no hover.
          The dasharray and offset together define the line position
          under the words. Here's also where the transition speed is set.
        */

        #shape {
            stroke-width: 6px;
            fill: transparent;
            stroke: darkred;
            stroke-dasharray: 85 400;
            stroke-dashoffset: -220;
            transition: 1s all ease;
        }
        /*
            Pushing the text up into the SVG. Without this the
            text would be below the div's.
        */

        #text {
            margin-top: -35px;
            text-align: center;
        }

        #text a {
            color: white;
            text-decoration: none;
            font-weight: 100;
            font-size: 1.1em;
        }
        /*
            Changing the shape on hover. I change the color of the stroke,
        make it thinner, then set it to again wrap around the entire parent element.
        */

        .svg-wrapper:hover #shape {
            stroke-dasharray: 50 0;
            stroke-width: 3px;
            stroke-dashoffset: 0;
            stroke: red;
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="sweetalert2.all.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function confdelete(){
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes!',
                cancelButtonText: 'No!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {
                    swalWithBootstrapButtons.fire(
                        'Deleted!',
                        'All Record Are Deleted.',
                        'Success'
                    );
                    function sleep(ms) {
                        return new Promise(resolve => setTimeout(resolve, ms));
                    }
                    async function valid() {
                        await sleep(3000);
                        window.location.replace("{{ path('deleteallrec') }}");
                    }
                    valid();
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Be Sure Before You Click :)'
                    )
                }
            });
        }
    </script>
{% endblock %}