src/Entity/Records.php
<?php

namespace App\Entity;

use App\Repository\RecordsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecordsRepository::class)
 */
class Records
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $User;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Score;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $WhiteTest;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Certification;

    /**
     * @ORM\Column(type="date", length=255)
     */
    private $Date;

    /**
     * @ORM\Column(type="integer")
     */
    private $Total;

    /**
     * @ORM\ManyToOne(targetEntity=User1::class, inversedBy="records")
     */
    private $User1;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?string
    {
        return $this->User;
    }

    public function setUser(string $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getScore(): ?string
    {
        return $this->Score;
    }

    public function setScore(string $Score): self
    {
        $this->Score = $Score;

        return $this;
    }

    public function getWhiteTest(): ?string
    {
        return $this->WhiteTest;
    }

    public function setWhiteTest(string $WhiteTest): self
    {
        $this->WhiteTest = $WhiteTest;

        return $this;
    }

    public function getCertification(): ?string
    {
        return $this->Certification;
    }

    public function setCertification(string $Certification): self
    {
        $this->Certification = $Certification;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->Total;
    }

    public function setTotal(int $Total): self
    {
        $this->Total = $Total;

        return $this;
    }

    public function getUser1(): ?User1
    {
        return $this->User1;
    }

    public function setUser1(?User1 $User1): self
    {
        $this->User1 = $User1;

        return $this;
    }
}

templates/Client/AddWhiteTest.html.twig
{%  extends "Client/base.html.twig" %}
{% block title %}Add WhiteTest{% endblock %}


{%  block comment  %}<!--Menu just replace the parent with the link here and add the word "active" to the class= for the current page name-->
<!-- <li class="nav-item active"><a href="" class="nav-link">Forum</a></li> -->{% endblock %}

{% block home %} {{ parent() }} {% endblock %}
{% block about %} {{ parent() }} {% endblock %}
{% block certifications %} {{ parent() }} {% endblock %}
{% block instructors %} {{ parent() }} {% endblock %}
{% block forum %}  {{ parent() }} {% endblock %}
{% block contact %} {{ parent() }} {% endblock %}


{%  block sectionname %} Add WhiteTest {% endblock %}
{% block sectionmenu %} Add WhiteTest {% endblock %}

{% block contenu %}
    <center>

        <div class="login-wrap p-4 p-md-5" style="margin-top: 5px;">
            <h1 class="unselectable hvr-hang-auto">Create A WhiteTest</h1>


        {{ form_start(form) }}

            <div class="form-group hvr-grow" style="width: 800px;">
            <label class="label" for="Title">Title</label>
             {{ form_widget(form.Title, {'attr': {'class': 'form-control'}}) }}
            </div>


            <div class="form-group hvr-grow" style="width: 800px;">
            <label class="label" for="Certification">Certification</label>
            {{ form_widget(form.Certification, {'attr': {'class': 'form-control form-select'}}) }}
            </div>


            <div class="form-group d-flex justify-content-end mt-4">
                <button type="submit" class="btn btn-primary submit"><span class="fa fa-paper-plane"></span></button>
            </div>
        {{ form_end(form) }}

        <div class="svg-wrapper" style="float: left;">
            <svg height="40" width="150" xmlns="http://www.w3.org/2000/svg">
                <rect id="shape" height="40" width="150" />
                <div id="text" >
                    &nbsp;<a href="{{ path('certification')}}"><span class="spot"></span><span style="color: #0b7dfd;">Certifications</span></a>
                </div>
            </svg>
        </div>
        </div>
    </center>
    <style>
        /*       Just setting CSS for the page   */

        * {
            margin: 0;
            padding: 0;
        }

        html,
        css {
            width: 100%;
            height: 100%;
        }

        .position {
            margin-left: auto;
            margin-right: auto;
            text-align: center;
            margin-top: 15%;
        }

        #workarea {
            position: absolute;
            width: 100%;
            height: 100%;
            background-color: #1e1a3e;
            font-family: Raleway;
        }

        #personal {
            color:white;
            text-decoration:none;
            position:absolute;
            bottom:15px;
            right:2%;
        }
        /*    start code for the actual button:         */


        /*
            Spot is the span on the inside of the href that
            fills the parent and makes the hover and link work
            for the entire div
        */

        .spot {
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
        }
        /*
            This is the outer svg wrapper that the SVG itself will
            fill. Multiple svg-wrapper classes can be put side by side.
        */

        .svg-wrapper {
            margin-top: 0;
            position: relative;
            width: 150px;
            /*make sure to use same height/width as in the html*/
            height: 40px;
            display: inline-block;
            border-radius: 3px;
            margin-left: 5px;
            margin-right: 5px
        }
        /*
          This is where we define the fill, color, thickness,
          and stroke pattern of the SVG when there is no hover.
          The dasharray and offset together define the line position
          under the words. Here's also where the transition speed is set.
        */

        #shape {
            stroke-width: 6px;
            fill: transparent;
            stroke: #009FFD;
            stroke-dasharray: 85 400;
            stroke-dashoffset: -220;
            transition: 1s all ease;
        }
        /*
            Pushing the text up into the SVG. Without this the
            text would be below the div's.
        */

        #text {
            margin-top: -35px;
            text-align: center;
        }

        #text a {
            color: white;
            text-decoration: none;
            font-weight: 100;
            font-size: 1.1em;
        }
        /*
            Changing the shape on hover. I change the color of the stroke,
        make it thinner, then set it to again wrap around the entire parent element.
        */

        .svg-wrapper:hover #shape {
            stroke-dasharray: 50 0;
            stroke-width: 3px;
            stroke-dashoffset: 0;
            stroke: #06D6A0;
        }
    </style>
{% endblock %}

templates/Client/EditWhiteTest.html.twig
{%  extends "Client/base.html.twig" %}
{% block title %}Add WhiteTest{% endblock %}


{%  block comment  %}<!--Menu just replace the parent with the link here and add the word "active" to the class= for the current page name-->
    <!-- <li class="nav-item active"><a href="" class="nav-link">Forum</a></li> -->{% endblock %}

{% block home %} {{ parent() }} {% endblock %}
{% block about %} {{ parent() }} {% endblock %}
{% block certifications %} {{ parent() }} {% endblock %}
{% block instructors %} {{ parent() }} {% endblock %}
{% block forum %}  {{ parent() }} {% endblock %}
{% block contact %} {{ parent() }} {% endblock %}


{%  block sectionname %} Add WhiteTest <div id="this"></div>{% endblock %}
{% block sectionmenu %} Add WhiteTest {% endblock %}

{% block contenu %}
    <div class="login-wrap p-4 p-md-5" style="margin-top: 5px;">
    <center>


            <h1 class="unselectable hvr-hang-auto">Edit A WhiteTest</h1>


            {{ form_start(form) }}

            <div class="form-group hvr-grow" style="width: 800px;">
                <label class="label" for="Title">Title</label>
                {{ form_widget(form.Title, {'attr': {'class': 'form-control'}}) }}
            </div>


            <div class="form-group hvr-grow" style="width: 800px;">
                <label class="label" for="Certification">Certification</label>
                {{ form_widget(form.Certification, {'attr': {'class': 'form-control form-select'}}) }}
            </div>


            <div class="form-group d-flex justify-content-end mt-4">
                <button type="submit" class="btn btn-primary submit"><span class="fa fa-paper-plane"></span></button>
            </div>
            {{ form_end(form) }}

    </center>

        <center>
            <div class="svg-wrapper-red">
            <svg height="40" width="150" xmlns="http://www.w3.org/2000/svg">
                <rect id="shape-red" height="40" width="150" />
                <div id="text" >
                    &nbsp;<a href="#this" onclick="confdelete()" ><span class="spot"></span><span style="color: black;">Delete</span></a>
                </div>
            </svg>
            </div>
        </center>

        <div class="svg-wrapper" style="float: left;">
            <svg height="40" width="150" xmlns="http://www.w3.org/2000/svg">
                <rect id="shape" height="40" width="150" />
                <div id="text" >
                    &nbsp;<a href="{{ path('white_test_index',{'certif':certif}) }}"><span class="spot"></span><span style="color: #0b7dfd;">Back To List</span></a>
                </div>
            </svg>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="sweetalert2.all.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        function confdelete(){
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes!',
                cancelButtonText: 'No!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {
                    swalWithBootstrapButtons.fire(
                        'Deleted!',
                        'WhiteTest Is Deleted.',
                        'Success'
                    );
                    function sleep(ms) {
                        return new Promise(resolve => setTimeout(resolve, ms));
                    }
                    async function valid() {
                        await sleep(3000);
                        window.location.replace("{{ path('deletewh', {'id': white_test.id,'certif':certif}) }}");
                    }
                    valid();
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Be Sure Which Test You Select :)'
                    )
                }
            });
        }
    </script>

    <style>
        /*       Just setting CSS for the page   */

        * {
            margin: 0;
            padding: 0;
        }

        html,
        css {
            width: 100%;
            height: 100%;
        }

        .position {
            margin-left: auto;
            margin-right: auto;
            text-align: center;
            margin-top: 15%;
        }

        #workarea {
            position: absolute;
            width: 100%;
            height: 100%;
            background-color: #1e1a3e;
            font-family: Raleway;
        }

        #personal {
            color:white;
            text-decoration:none;
            position:absolute;
            bottom:15px;
            right:2%;
        }
        /*    start code for the actual button:         */


        /*
            Spot is the span on the inside of the href that
            fills the parent and makes the hover and link work
            for the entire div
        */

        .spot {
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
        }
        /*
            This is the outer svg wrapper that the SVG itself will
            fill. Multiple svg-wrapper classes can be put side by side.
        */

        .svg-wrapper {
            margin-top: 0;
            position: relative;
            width: 150px;
            /*make sure to use same height/width as in the html*/
            height: 40px;
            display: inline-block;
            border-radius: 3px;
            margin-left: 5px;
            margin-right: 5px
        }
        .svg-wrapper-red {
            margin-top: 0;
            position: relative;
            width: 150px;
            /*make sure to use same height/width as in the html*/
            height: 40px;
            display: inline-block;
            border-radius: 3px;
            margin-left: 5px;
            margin-right: 5px
        }
        .svg-wrapper-green {
            margin-top: 0;
            position: relative;
            width: 150px;
            /*make sure to use same height/width as in the html*/
            height: 40px;
            display: inline-block;
            border-radius: 3px;
            margin-left: 5px;
            margin-right: 5px
        }
        /*
          This is where we define the fill, color, thickness,
          and stroke pattern of the SVG when there is no hover.
          The dasharray and offset together define the line position
          under the words. Here's also where the transition speed is set.
        */

        #shape {
            stroke-width: 6px;
            fill: transparent;
            stroke: #009FFD;
            stroke-dasharray: 85 400;
            stroke-dashoffset: -220;
            transition: 1s all ease;
        }
        #shape-red {
            stroke-width: 6px;
            fill: transparent;
            stroke: darkred;
            stroke-dasharray: 85 400;
            stroke-dashoffset: -220;
            transition: 1s all ease;
        }
        #shape-green {
            stroke-width: 6px;
            fill: transparent;
            stroke: green;
            stroke-dasharray: 85 400;
            stroke-dashoffset: -220;
            transition: 1s all ease;
        }
        /*
            Pushing the text up into the SVG. Without this the
            text would be below the div's.
        */

        #text {
            margin-top: -35px;
            text-align: center;
        }

        #text a {
            color: white;
            text-decoration: none;
            font-weight: 100;
            font-size: 1.1em;
        }
        /*
            Changing the shape on hover. I change the color of the stroke,
        make it thinner, then set it to again wrap around the entire parent element.
        */

        .svg-wrapper:hover #shape {
            stroke-dasharray: 50 0;
            stroke-width: 3px;
            stroke-dashoffset: 0;
            stroke: #06D6A0;
        }
        .svg-wrapper-red:hover #shape-red {
            stroke-dasharray: 50 0;
            stroke-width: 3px;
            stroke-dashoffset: 0;
            stroke: red;
        }
        .svg-wrapper-green:hover #shape-green {
            stroke-dasharray: 50 0;
            stroke-width: 3px;
            stroke-dashoffset: 0;
            stroke: greenyellow;
        }
    </style>

{% endblock %}

templates/Client/about.html.twig
{%  extends "Client/base.html.twig" %}
{% block title %}{{ parent() }}{% endblock %}


{%  block comment  %}<!--Menu just replace the parent with the link here and add the word "active" to the class= for the current page name-->
    <!-- <li class="nav-item active"><a href="" class="nav-link">Forum</a></li> -->{% endblock %}

{% block home %} {{ parent() }} {% endblock %}
{% block about %}<li class="nav-item active"><a href="{{ path("about") }}" class="nav-link hvr-float">About</a></li>{% endblock %}
{% block certifications %}<li class="nav-item"><a href="{{ path("certification") }}" class="nav-link hvr-float">Certifications</a></li>{% endblock %}
{% block instructors %} {{ parent() }} {% endblock %}
{% block forum %}  {{ parent() }} {% endblock %}
{% block contact %} {{ parent() }} {% endblock %}


{%  block sectionname %} About Us {% endblock %}
{% block sectionmenu %}  Main {% endblock %}
{% block contenu %}

    <section class="ftco-section ftco-about img">
        <div class="container">
            <div class="row d-flex">
                <div class="col-md-12 about-intro">
                    <div class="row">
                        <div class="col-md-6 d-flex">
                            <div class="d-flex about-wrap">
                                <div class="img d-flex align-items-center justify-content-center" style="background-image:url({{ asset("assets/Client/images/about-1.jpg") }});">
                                </div>
                                <div class="img-2 d-flex align-items-center justify-content-center" style="background-image:url({{ asset("assets/Client/images/about.jpg") }});">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 pl-md-5 py-5">
                            <div class="row justify-content-start pb-3">
                                <div class="col-md-12 heading-section">
                                    <span class="subheading">Enhanced Your Skills</span>
                                    <h2 class="mb-4">Learn Anything You Want Today</h2>
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                                    <p><a href="{{ path("contact_new") }}" class="btn btn-primary hvr-float-shadow">Get in touch with us</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>





{% endblock %}

templates/Client/addquestion.html.twig
{%  extends "Client/base.html.twig" %}
{% block title %}Add WhiteTest{% endblock %}


{%  block comment  %}<!--Menu just replace the parent with the link here and add the word "active" to the class= for the current page name-->
    <!-- <li class="nav-item active"><a href="" class="nav-link">Forum</a></li> -->{% endblock %}

{% block home %} {{ parent() }} {% endblock %}
{% block about %} {{ parent() }} {% endblock %}
{% block certifications %} {{ parent() }} {% endblock %}
{% block instructors %} {{ parent() }} {% endblock %}
{% block forum %}  {{ parent() }} {% endblock %}
{% block contact %} {{ parent() }} {% endblock %}


{%  block sectionname %} Add A Question {% endblock %}
{% block sectionmenu %} Question {% endblock %}

{% block contenu %}
    <div class="login-wrap p-4 p-md-5" style="margin-top: 5px;">
    <center>



            <h1 class="unselectable hvr-hang-auto">Add A New Question</h1>


            {{ form_start(form) }}

            <div class="form-group hvr-grow" style="width: 800px;">
                <label class="label" for="Title">Answer</label>
                {{ form_widget(form.Answer, {'attr': {'class': 'form-control'}}) }}
            </div>

        <div class="form-group hvr-grow" style="width: 800px;">
            <label class="label" for="Title">Question</label>
            {{ form_widget(form.Question, {'attr': {'class': 'form-control'}}) }}
        </div>

        <div class="form-group hvr-grow" style="width: 800px;">
            <label class="label" for="Title">ChoiceA</label>
            {{ form_widget(form.ChoiceA, {'attr': {'class': 'form-control'}}) }}
        </div>

        <div class="form-group hvr-grow" style="width: 800px;">
            <label class="label" for="Title">ChoiceB</label>
            {{ form_widget(form.ChoiceB, {'attr': {'class': 'form-control'}}) }}
        </div>

        <div class="form-group hvr-grow" style="width: 800px;">
            <label class="label" for="Title">ChoiceC</label>
            {{ form_widget(form.ChoiceC, {'attr': {'class': 'form-control'}}) }}
        </div>

        <div class="form-group hvr-grow" style="width: 800px;">
            <label class="label" for="Title">Duration</label>
            {{ form_widget(form.Duration, {'attr': {'class': 'form-control'}}) }}
        </div>

        <div class="form-group hvr-grow" style="width: 800px;">
            <label class="label" for="Title">WhiteTest</label>
            {{ form_widget(form.whiteTest, {'attr': {'class': 'form-control select'}}) }}
        </div>

            <div class="form-group d-flex justify-content-end mt-4">
                <button type="submit" class="btn btn-primary submit"><span class="fa fa-paper-plane"></span></button>
            </div>
            {{ form_end(form) }}

    </center>




        <div class="svg-wrapper" style="float: left;">
            <svg height="40" width="150" xmlns="http://www.w3.org/2000/svg">
                <rect id="shape" height="40" width="150" />
                <div id="text" >
                    &nbsp;<a href="{{ path('question_crud_index') }}"><span class="spot"></span><span style="color: #0b7dfd;">Questions List</span></a>
                </div>
            </svg>
        </div>


    </div>


    <style>
        /*       Just setting CSS for the page   */

        * {
            margin: 0;
            padding: 0;
        }

        html,
        css {
            width: 100%;
            height: 100%;
        }

        .position {
            margin-left: auto;
            margin-right: auto;
            text-align: center;
            margin-top: 15%;
        }

        #workarea {
            position: absolute;
            width: 100%;
            height: 100%;
            background-color: #1e1a3e;
            font-family: Raleway;
        }

        #personal {
            color:white;
            text-decoration:none;
            position:absolute;
            bottom:15px;
            right:2%;
        }
        /*    start code for the actual button:         */


        /*
            Spot is the span on the inside of the href that
            fills the parent and makes the hover and link work
            for the entire div
        */

        .spot {
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
        }
        /*
            This is the outer svg wrapper that the SVG itself will
            fill. Multiple svg-wrapper classes can be put side by side.
        */

        .svg-wrapper {
            margin-top: 0;
            position: relative;
            width: 150px;
            /*make sure to use same height/width as in the html*/
            height: 40px;
            display: inline-block;
            border-radius: 3px;
            margin-left: 5px;
            margin-right: 5px
        }
        .svg-wrapper-red {
            margin-top: 0;
            position: relative;
            width: 150px;
            /*make sure to use same height/width as in the html*/
            height: 40px;
            display: inline-block;
            border-radius: 3px;
            margin-left: 5px;
            margin-right: 5px
        }
        .svg-wrapper-green {
            margin-top: 0;
            position: relative;
            width: 150px;
            /*make sure to use same height/width as in the html*/
            height: 40px;
            display: inline-block;
            border-radius: 3px;
            margin-left: 5px;
            margin-right: 5px
        }
        /*
          This is where we define the fill, color, thickness,
          and stroke pattern of the SVG when there is no hover.
          The dasharray and offset together define the line position
          under the words. Here's also where the transition speed is set.
        */

        #shape {
            stroke-width: 6px;
            fill: transparent;
            stroke: #009FFD;
            stroke-dasharray: 85 400;
            stroke-dashoffset: -220;
            transition: 1s all ease;
        }
        #shape-red {
            stroke-width: 6px;
            fill: transparent;
            stroke: darkred;
            stroke-dasharray: 85 400;
            stroke-dashoffset: -220;
            transition: 1s all ease;
        }
        #shape-green {
            stroke-width: 6px;
            fill: transparent;
            stroke: green;
            stroke-dasharray: 85 400;
            stroke-dashoffset: -220;
            transition: 1s all ease;
        }
        /*
            Pushing the text up into the SVG. Without this the
            text would be below the div's.
        */

        #text {
            margin-top: -35px;
            text-align: center;
        }

        #text a {
            color: white;
            text-decoration: none;
            font-weight: 100;
            font-size: 1.1em;
        }
        /*
            Changing the shape on hover. I change the color of the stroke,
        make it thinner, then set it to again wrap around the entire parent element.
        */

        .svg-wrapper:hover #shape {
            stroke-dasharray: 50 0;
            stroke-width: 3px;
            stroke-dashoffset: 0;
            stroke: #06D6A0;
        }
        .svg-wrapper-red:hover #shape-red {
            stroke-dasharray: 50 0;
            stroke-width: 3px;
            stroke-dashoffset: 0;
            stroke: red;
        }
        .svg-wrapper-green:hover #shape-green {
            stroke-dasharray: 50 0;
            stroke-width: 3px;
            stroke-dashoffset: 0;
            stroke: greenyellow;
        }
    </style>




{% endblock %}

templates/Client/chosewh.html.twig
{%  extends "Client/base.html.twig" %}
{% block title %}Add WhiteTest{% endblock %}


{%  block comment  %}<!--Menu just replace the parent with the link here and add the word "active" to the class= for the current page name-->
    <!-- <li class="nav-item active"><a href="" class="nav-link">Forum</a></li> -->{% endblock %}

{% block home %} {{ parent() }} {% endblock %}
{% block about %} {{ parent() }} {% endblock %}
{% block certifications %} {{ parent() }} {% endblock %}
{% block instructors %} {{ parent() }} {% endblock %}
{% block forum %}  {{ parent() }} {% endblock %}
{% block contact %} {{ parent() }} {% endblock %}


{%  block sectionname %} Certifications {% endblock %}
{% block sectionmenu %} Chose A Certification {% endblock %}

{% block contenu %}
    <center>
        <table >

            <tr>
                <td><a href="{{ path('white_test_index',{'certif':'OCP'}) }}"><img src="{{ asset("assets/ocp.png")}}">&nbsp;&nbsp;&nbsp;&nbsp;</a></td>
            <td><a href="{{ path('white_test_index',{'certif':'CEH'}) }}"><img src="{{ asset("assets/ceh.png")}}">&nbsp;&nbsp;&nbsp;&nbsp;</a></td>
            <td><a href="{{ path('white_test_index',{'certif':'CISCO'}) }}"><img src="{{ asset("assets/cisco.png")}}"></a></td>
            </tr>
        </table>
    </center>
    <style>
        img {
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 5px;
            width: 150px;
            height: 150px;
        }
    </style>
{% endblock %}

templates/Client/test.html.twig
{%  extends "Client/base.html.twig" %}
{% block title %}{{ parent() }}{% endblock %}


{%  block comment  %}<!--Menu just replace the parent with the link here and add the word "active" to the class= for the current page name-->
<!-- <li class="nav-item active"><a href="" class="nav-link">Forum</a></li> -->{% endblock %}

{% block home %} {{ parent() }} {% endblock %}
{% block about %} {{ parent() }} {% endblock %}
{% block certifications %} {{ parent() }} {% endblock %}
{% block instructors %} {{ parent() }} {% endblock %}
{% block forum %}  {{ parent() }} {% endblock %}
{% block contact %} {{ parent() }} {% endblock %}


{%  block sectionname %} Test {% endblock %}
{% block sectionmenu %} Test {% endblock %}
{% block contenu %} Test {% endblock %}